### ISSUE TITLE
Preparing the train and validation data in .pt format from coco format json file

### ISSUE THREAD

**Issue by guanyichen** [ChristophReich1996/Cell-DETR#8]
Hi Christoph,

Thank you so much for providing the code and the explanations. It is really a brilliant work.
I would like to use the Cell-DETR model for the detection and segmentation of a single object in order to study the DETR.
However, I met some problem when I prepared the train and validation data.

**First step**
I completed image annotations by the tool [Labelme](https://github.com/wkentaro/labelme). This tool can convert to VOC-format or to COCO-format.([Labelme convert format details](https://github.com/wkentaro/labelme/tree/master/examples/instance_segmentation#convert-to-voc-format-dataset))

**Second step**
After complete annotations, I convert all the related files into a single json file with COCO json format.
([View the example json file here](https://github.com/guanyichen/coco-format-json-file/blob/main/roadscene_val.json))

However, I'm really confused about how to prepare the data structured in bounding boxes, classes, inputs, and instances. 
As for the input images, the following method may work.
```
import torchvision.transforms
pil_to_tensor = transforms.ToTensor()(img).unsqueeze_(0)
```
As for the bounding boxes, classes, and instances, should I manually edit and save as tensors in .pt files?
Could you please elaborate the above process?
Do you have any idea how to complete preparing the train and validation data in batch?
Would you please share the details how you prepare the data structured in bounding boxes, classes, inputs, and instances?
Thanks in advance.

Best regards,
Simon

**Comment by ChristophReich1996** [comment]
Hi Simon,

thanks for your interest. So we used a kinda special format, to be precise we stored the dataset as raw tensors in the [PyTorch file format](https://pytorch.org/docs/stable/generated/torch.save.html). You can find a detailed description of the data format in this issue #3 . If you want to utilize data in the COCO format I would say there are two options. First, you could convert your dataset to our special format, or second, you could write your own dataset classes. Either way, I guess it would be cool if you implemented a COCO to .pt script or a COCO dataset class to open a pull request to help others with the same issue :)

PS: If you want to detect/segment a single object this issue might be interesting for you #4, since reducing the number of query positions is might be useful.

Cheers
Christoph
